### PR TITLE
Pull eustas/ngx_brotli fork

### PR DESCRIPTION
**Pull request by eustas**

### CODE REVIEW

**Comment by eustas** [comment]
@felixbuenemann could you provide your consent to CLA system, please!
Thanks =)

**Comment by lvandeve** [comment]
Looks good to me, waiting for the consent now

**Comment by felixbuenemann** [comment]
@googlebot I consent.

**Comment by felixbuenemann** [comment]
@eustas Is the above comment enough to consent to the CLA?

**Pull request merged**
